name: Run audit

on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Setup caching dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Fetch dependencies
        run: cargo fetch --target wasm32-unknown-unknown

      - name: Run audit
        run: cargo audit
