name: Build contract

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-contract:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/partisia/dockerimages/rustmaven:1.74

    steps:
      - uses: actions/checkout@v3

      - name: Set default rust version
        run: rustup default 1.74

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup caching dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install partisia-contract
        run: cargo install cargo-partisia-contract

      - name: Fetch dependencies
        run: cargo fetch --target wasm32-unknown-unknown

      - name: Build contracts
        run: |
          cargo partisia-contract build --release
          cd target/wasm32-unknown-unknown/release
          zip meta_names_contract.zip meta_names_contract.wasm meta_names_contract.abi
          zip proxy_contract.zip contract_proxy.wasm contract_proxy.abi
          zip voting_contract.zip contract_voting.wasm contract_voting.abi

      - name: Upload meta names contract artifact
        uses: actions/upload-artifact@v4
        with:
          name: meta_names_contract
          path: target/wasm32-unknown-unknown/release/meta_names_contract.zip

      - name: Upload proxy contract artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy_contract
          path: target/wasm32-unknown-unknown/release/proxy_contract.zip

      - name: Upload voting contract artifact
        uses: actions/upload-artifact@v4
        with:
          name: voting_contract
          path: target/wasm32-unknown-unknown/release/voting_contract.zip
