name: Main

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  audit:
    uses: ./.github/workflows/audit.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: audit

  wasm-check:
    uses: ./.github/workflows/wasm-check.yml
    needs: audit

  build-contract:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: registry.gitlab.com/partisia/dockerimages/rustmaven:1.67

    steps:
      - uses: actions/checkout@v3

      - name: Setup caching dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install partisia-contract
        run: cargo install cargo-partisia-contract

      - name: Fetch dependencies
        run: cargo fetch --target wasm32-unknown-unknown

      - name: Build release contract
        run: |
          cargo partisia-contract build --release
          cd target/wasm32-unknown-unknown/release
          zip meta_names_contract.zip meta_names_contract.wasm meta_names_contract.abi

      - name: Upload contract artifacts
        uses: actions/upload-artifact@v2
        with:
          name: meta_names_contract
          path: target/wasm32-unknown-unknown/release/meta_names_contract.zip
