name: Main

on:
  push:
    branches: [main]

jobs:
  audit:
    uses: ./actions/audit.yml

  test:
    uses: ./actions/test.yml
    needs: audit

  wasm-check:
    uses: ./actions/wasm-check.yml
    needs: audit

  build-contract:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Setup caching dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --target wasm32-unknown-unknown

      - name: Build release contract
        run: |
        cargo partisia-contract build --release
        cd target/wasm32-unknown-unknown/release
        zip meta_names_contract.zip meta_names_contract.wasm meta_names_contract.abi

      - name: Upload contract artifacts
        uses: actions/upload-artifact@v2
        with:
          name: meta_names_contract
          path: target/wasm32-unknown-unknown/release/meta_names_contract.zip
