name: Main

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  audit:
    uses: ./.github/workflows/audit.yml

  build-contract:
    uses: ./.github/workflows/build-contract.yml
    needs: test

  test:
    uses: ./.github/workflows/test.yml
    needs: wasm-check

  wasm-check:
    uses: ./.github/workflows/wasm-check.yml
    needs: audit
