name: Run tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/partisia/dockerimages/rustmaven:1.67

    steps:
      - uses: actions/checkout@v3

      - name: Set default rust version
        run: rustup default 1.67

      - name: Setup caching dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --target wasm32-unknown-unknown

      - name: Run tests
        run: cargo test
