name: Run wasm check

on:
  workflow_call:

jobs:
  wasm-check:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/partisia/dockerimages/rustmaven:1.74

    steps:
      - uses: actions/checkout@v3

      - name: Set default rust version
        run: rustup default 1.74

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup caching dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --target wasm32-unknown-unknown

      - name: Check build
        run: cargo check --all-features --target wasm32-unknown-unknown
