name: Run wasm check

on:
  workflow_call:

jobs:
  wasm-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.69.0
          target: wasm32-unknown-unknown

      - name: Setup caching dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --target wasm32-unknown-unknown

      - name: Check build
        run: cargo check --all-features --target wasm32-unknown-unknown
